### ISSUE TITLE
Compile the binaries from source

### ISSUE THREAD

**Issue by michele13** [termux/termux-docker#6]
How did you get the libraries and binaries to make the docker container? Can you provide instructions on how to build them? 
I'm really interested in how to compile/obtain the latest development versions of those to make some tests

**Comment by xeffyr** [comment]
> How did you get the libraries and binaries to make the docker container?

Binaries are extracted from Android 9.0 virtual device images provided by Google. I have copied only exactly what is used by Termux (linker, libc, liblog and deps) and minimal set of utilities for `/system/bin`.

> Can you provide instructions on how to build them?

None of the available binaries were built from source.

If you are interested for doing so, you should look for instructions of building Android from sources. I won't re-post them here.

**Comment by robertkirkman** [comment]
@michele13 I would like to let you know, in case this problem still bothers you,

that while this issue was closed as "completed" without recompiling the binaries from source,

that I have actually recompiled all of the binaries from source, and that this version which I did that to is now the official version, and the source code currently present in the repository shows exactly how to do that now, after this PR:

- #72 

and I added the other source code in another repository, in this PR, which you can see also, and I hope you can see how this repository is now connected to the code in that repository:

- https://github.com/termux/termux-packages/pull/22906

I hope this is satisfactory to you!
